py
site_name: Sava Osiguranje Dokumentacija
theme:
  name: material
  favicon: images/savalogo.png
  language: sh
  font:
    text: Roboto
  icon:
    logo: fontawesome/solid/book
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigaion.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    -typeset
    -search
   
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night 
        name: Promeni u tamnu pozadinu

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Promeni u svetlu pozadinu

markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences
 - attr_list
 - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
 - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
 - toc:
    permalink: true

copyright: Copyright &copy; 2023 Sava Osiguranje

extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sava_osiguranje_srbija/?hl=en
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/sava.osiguranje.srbija/
    - icon:  fontawesome/brands/twitter
      link: https://twitter.com/savaosiguranje?lang=en

nav:
  - POČETNA: index.md
  - OSIGURANJA: 
    - 'Opis osiguranja': osiguranja/opisOsiguranja.md
    - 'AUTO POLISE':
      - 'Izgled': osiguranja/auto.md
      - 'Opis': osiguranja/autoOpis.md
    - 'PUTNO': 
      - 'Izgled': osiguranja/putno.md
      - 'Opis': osiguranja/putnoOpis.md
    - 'DOMAĆINSTVO':
      - 'Izgled': osiguranja/domacinstvo.md
      - 'Opis': osiguranja/domacinstvoOpis.md



